Prime the index registry using current cargo

diff --git a/.github/workflows/rust-1.10.yml b/.github/workflows/rust-1.10.yml
--- a/.github/workflows/rust-1.10.yml
+++ b/.github/workflows/rust-1.10.yml
@@ -16,7 +16,7 @@ jobs:
         shell: bash
         # Point cargo at a rewound copy of crates.io that is still understood at 1.10.0.
         run: |
-          set -e
+          set -ex
           mkdir -p .cargo
           cat <<EOF > .cargo/config
           [sources.crates-io]
@@ -27,6 +27,10 @@ jobs:
           cd crates-io-rewound
           # Reset to a point where rand 0.8.0 didn't exist in index.
           git reset --hard 46a429eac9f
+          # Prime the index registry using current cargo
+          cargo build --manifest-path vcpkg/Cargo.toml --verbose
+          # Clean up so rust 1.10.0 does its build.
+          cargo clean
       - name: Set default Rust
         run: rustup default 1.10.0
       - name: Run build
